name: Python CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        
    - name: Install tox
      run: pip install tox
      
    - name: Run CI with tox
      run: tox
